### ISSUE TITLE
pw-cli create-node adapter creating mono adapter

### ISSUE THREAD

**Issue by thulle** [d-wid/pipewire-eq-startup-script#1]
Great introduction to scripting this!

I had issues with this command though:
pw-cli create-node adapter { factory.name=support.null-audio-sink node.name="$NODENAME" media.class=Audio/Sink object.linger=1 audio.position=FL,FR }

using pipewire 0.3.34 on gentoo this created a mono adapter with only the first listed audio.position. 

Changing it to  audio.position=[ FL FR ] created the expected stereo interface.

**Comment by d-wid** [comment]
Hi, thanks for the heads-up. I'm going to have to take your word for it since I don't have Pipewire 0.3.34 myself, but the relevant Wiki pages seem to have been "updated" to what you're suggesting so I suppose it's a recent-ish change made in Pipewire itself. Making those changes to the script and trying to run it on Pipewire 0.3.19 didn't go well.

Is this your first time trying the script out or have you had it previously work on an earlier version (i.e. if you're in a position to confirm it was working the way I uploaded it as recently as 0.3.33 then I'd love to know :D)?

**Comment by thulle** [comment]
I just switched to pipewire yesterday, realized how easy it was to add a parametric equalizer, and searching for how to comfortably reconnect everything at login I found this script. :)

I'm a bit busy today, but it's easy for me to switch between versions, so I can check 0.3.33 to 0.3.19 to check where the change is made and if there's some overlap where both ways work, and get back to you.

**Comment by d-wid** [comment]
Oops sorry I cliked the wrong button there. Didn't mean to close the issue!

Thanks! In the mean time (or if you end up never getting around to it for one reason or another) I guess I'll just make the script contain both versions and ask users to comment/uncomment accordingly (makes the script more complicated to use but it's probably the best solution in the end anyway, short using the pactl equivalent and adding yet another dependency).

**Comment by thulle** [comment]
In 0.3.25 both ways (FL,FR & [ FL FR ]) to specify it works, in 0.3.26 only the latter way works.

**Comment by thulle** [comment]
Without spending too much time getting in to the code it seems to be due to this commit making it into 0.3.26:
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/fa3bd6b0e1ae493f72d10668723dd5842ff0a2de

**Comment by d-wid** [comment]
Awesome, that's great to know. And thank you too for looking into Pipewire's code! Damn, that's commit looks older than this repository itself.

**Comment by d-wid** [comment]
The script should be working now. Feel free to test it again (though it's probably already much the same as whatever you already got to run, apart from some comments).
